### ISSUE TITLE
-- following from time to time repeats content

### ISSUE THREAD

**Issue by lucagrulla** [lucagrulla/cw#1]
the --following feature randomly repeats logs.

**Comment by fleaz** [comment]
Hi,
I'm running 3.2.2 and I'm also hitting this bug. When there is new content flowing into the stream, everything is fine. But when the stream is idle, cw will repeat the last two lines of the stream about every 65 seconds.

**Comment by lucagrulla** [comment]
Hi @fleaz, this might be related to #85 PR.
I'll have a look as soon as possobile to the PR and keep you posted.

**Comment by fleaz** [comment]
Hey, just wanted to confirm that with 3.2.4 the problem is gone :) 
Thank you!
