### ISSUE TITLE
Tail multiple log groups

### ISSUE THREAD

**Issue by nzoschke** [lucagrulla/cw#10]
A feature request for this tool is the ability to tail multiple groups.

This would be extremely useful for Lambda, where an "app" is composed of many Lambda functions, and each function has its own log groups.

I'd like to be able to `cw tail /aws/lambda/*`:

<img width="439" alt="36343700-5318e1e6-13c4-11e8-936c-465e02cac760" src="https://user-images.githubusercontent.com/147410/36645859-cd44c16e-1a23-11e8-8751-cd48ec751c14.png">

Would you consider a PR with the feature?

**Comment by lucagrulla** [comment]
Thanks for the offer

How would you guarantee that your logs are  interleaved? 

The risk is that the log would keep jumping forward and backward in time based on which log group is pushing to stdout.

**Comment by nzoschke** [comment]
I see this feature as a convenience during development and debugging, and am ok with trading off ordering across log groups for this usage.

So I was considering starting with a simple implementation that starts a `Tail` for every log group in a goroutine, and yes timestamps would not be strictly increasing in this case.

I can imagine a more coordinated approach too, but I'm not sure the complexity is worth it.

**Comment by lucagrulla** [comment]
I like the idea to track also lambdas logs; I want also to respect as much as I can the natural contract of tail where there's an implicit concept of time. 

I'd like to suggest two extra elements to your PR:
- an additional flag to print the log group(--group, -r)
- an additional flag to colour consistently logs from the same log group(--colour, -c)

These could help people in identifying which groups they are looking at, even if the timeline if not linear.

**Comment by lucagrulla** [comment]
Hey @nzoschke I assume you're not interested in sending the PR anymore?

**Comment by nzoschke** [comment]
@lucagrulla, I have not found any time to work on this, and don't see doing so anytime soon. Sorry!

**Comment by lucagrulla** [comment]
No worries @nzoschke.
Thanks for the idea anyway!
