### ISSUE TITLE
Not able to connect may be because of proxy

### ISSUE THREAD

**Issue by santhosh-v** [lucagrulla/cw#104]
**Is your feature request related to a problem? Please describe.**
Not able to connect. Getting send request failed

**Describe the solution you'd like**
Add support for proxy

**Comment by lucagrulla** [comment]
Hi @santhosh-v 

Thanks for filing this issue.

I do need a little more details: what do you meamn with "not able to connect because of proxy"? Can you describe your network setup and how you envision the tool to work with a proxy?

**Comment by djw4** [comment]
I think what @santhosh-v  was referring to is that behind a proxy the application seems to fail unexpectedly, I having a similar issue behind an enterprise-wide Zscaler proxy:

```bash
~> cw tail -f app-stg03-logs -b3h
send request failed
```

My AWS credentials are all valid, no issues at all there. Does the app currently honour `$http_proxy` or `$https_proxy` values?

**Comment by lucagrulla** [comment]
Hi @djw4 

Thanks for the clarification.
cw does not explicitly manipulate any HTTP header for proxy support at this stage.

@djw4  Have you tried using the env variable as suggested for the AWS cli?
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html

```bash
export HTTP_PROXY=http://10.15.20.25:1234
```

Does it work with it?
