### ISSUE TITLE
panic because close of closed chanel

### ISSUE THREAD

**Issue by stephencheng** [lucagrulla/cw#11]
Hit the panic scenario which Tail method was called multiple times, or you have a little more time delay so that the Ticker fired more signal to trigger the page handler, which then try to close the closed chanel.

Using the Ticker is a little problematic here as it has no exit but rely on the chanel being closed and also does not allow caller to reconsume the Tail method.

I have used a fix of using the removed Ticker, it just worked fine.

**Comment by lucagrulla** [comment]
I can see the scenario you are referring to. 
How did you hit this bug? I have never had the problem...
