### ISSUE TITLE
Add flag to specify aws endpoint url

### ISSUE THREAD

**Issue by cbuschka** [lucagrulla/cw#120]
**Is your feature request related to a problem? Please describe.**
We develop locally with localstack. I would like use the same tooling locally as on aws. I.e. I would like point cw to the url of my localstack and tail logs via cw as if it where the real aws.

I currently see no way how to point cw to localstack.

**Describe the solution you'd like**
Add a command line flag "--endpoint-url" analogous to the flag of aws cli with same name. So the call to tail logs from localstack would be:

```
./cw --endpoint-url=http://localhost:4566 tail -f /aws/lambda/input-processor-lambda
```

**Describe alternatives you've considered**
No alternatives considered yet.

**Additional context**
No additional information yet.

**Comment by cbuschka** [comment]
Ok, I did a quick implementation. It works for me locally with localstack.

I would appreciate if the changes get merged. If it should be implemented in a different way or you see a better solution please elaborate on it.

**Comment by lucagrulla** [comment]
hi @cbuschka 
Thanks for the PR. It's now merged.
I'm having issues in the release process (snapcraft is failing). 
As soon as I underastand why it rejects this release this will be released across all the plaftform.

**Comment by cbuschka** [comment]
No need to hurry. If I can support, drop me a note.

**Comment by lucagrulla** [comment]
Fixed.
V3.3.0 is out.

**Comment by cbuschka** [comment]
Awesome! Thank you for the quick release!
