### ISSUE TITLE
Package name conflict with Ubuntu package

### ISSUE THREAD

**Issue by gene1wood** [lucagrulla/cw#134]
**Describe the bug**
The package name that you're using for the debian package, [`cw`](https://github.com/lucagrulla/cw/releases/tag/v3.3.0) conflicts with this package name in Ubuntu : https://launchpad.net/ubuntu/bionic/amd64/cw

As a result, if a user has both packages they replace each other depending on which one is installed last. 

**To Reproduce**
1. On an Ubuntu system run `sudo apt install cw`
2. run `wget https://github.com/lucagrulla/cw/releases/download/v3.3.0/cw_amd64.deb && sudo dpkg -i cw_amd64.deb`

**Expected behavior**
The existing `cw` package wouldn't be replaced and the CloudWatch tool would have a non conflicting name

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Terminal : any

**Comment by lucagrulla** [comment]
Thanks for the PR. 
I'll review and if all makes sense I'll merge.
