### ISSUE TITLE
scoop windows install in being block by antivirus

### ISSUE THREAD

**Issue by narsinallamilli** [lucagrulla/cw#140]
PS C:\Users\Narsi Nallamilli> Get-Host | Select-Object Version                  
Version
-------
5.1.18362.752

PS C:\Users\Narsi Nallamilli> iwr -useb get.scoop.sh | iex                      
iex : At line:1 char:1
+ #Requires -Version 5
+ ~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
At line:1 char:26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by lucagrulla** [comment]
Hi,

This is a potential bug with Scoop, now with cw.
Please file it here: https://github.com/lukesampson/scoop/issues

**Comment by narsinallamilli** [comment]
@lucagrulla  Is there any other way to install on Windows? Please help

**Comment by lucagrulla** [comment]
go to the release page:
https://github.com/lucagrulla/cw/releases

and from the latest release download the correct Windows archive.
Decompress the archive and install in the relevant folder.
