### ISSUE TITLE
Retry if log group does not exist (like tail -F/--retry)

### ISSUE THREAD

**Issue by JoshCooley** [lucagrulla/cw#141]
**Is your feature request related to a problem? Please describe.**
I'm working on a script that starts an ECS task and then tails the log from Cloudwatch. I wait until the task is actually in RUNNING state before kicking off cw, but there's still a few seconds between that state transition and the creation of the log group, so `cw` 
errors out with "The specified log group does not exist."

**Describe the solution you'd like**
`tail` has the following options:
```
-F     same as --follow=name --retry
...
--retry keep trying to open a file if it is inaccessible
```
Basically I'd like to see `-F` replicated in cw. If the log group doesn't exist, retry until it does. Emit STDERR messages if the initial log group check fails, if the log group appears, and if the log group disappears.
My script already kills cw when the task has completed, so there's no concern about the log group never appearing.

**Describe alternatives you've considered**
I can test if the log group exists myself, and wait to invoke `cw` until it does exist.

**Additional context**
As inspiration for the type of output I'd like to see here's `tail`'s STDERR output when following a file that does not exist on invocation, appears while `tail` is running, and is then deleted while `tail` is running: 
```
$ tail -F /tmp/logfile > /dev/null
tail: cannot open '/tmp/logfile' for reading: No such file or directory
tail: '/tmp/logfile' has appeared;  following new file
tail: '/tmp/logfile' has become inaccessible: No such file or directory
```

**Comment by lucagrulla** [comment]
hi @JoshCooley 

I can see the value of this additional flag.
I'd welcome a good PR if that something you'd be up for.

**Comment by lucagrulla** [comment]
Avaialable from v4.0.0
