### ISSUE TITLE
--profile flag

### ISSUE THREAD

**Issue by jnst** [lucagrulla/cw#17]
Thanks for nice tool 😃
I want to use the `--profile` flag like below to specify other aws credential profile.

```bash
$ cw --profile second ls groups
```

```setting
[default]
aws_access_key_id = ****
aws_secret_access_key = ****

[second]
aws_access_key_id = ****
aws_secret_access_key = ****
```

**Comment by lucagrulla** [comment]
It sounds neat.

A PR with this feature would be welcomed :-)

**Comment by lucagrulla** [comment]
Added with release 1.7.0.

**Comment by jnst** [comment]
Thanks for update! <3

But It doesn't works.
Even if I specified a `--profile` like below, the default profile was used.

```
$ cw --profile=second ls groups

/aws/codebuild/***
/aws/lambda/***

A new version of cw is available! - 1.7.0 -> v1.7.0
```

I tried both install `go get` and `brew`.

**Comment by jnst** [comment]
@lucagrulla 
Thanks for update! <3

But It doesn't works.
Even if I specified a `--profile` like below, the default profile was used.

```
$ cw --profile=second ls groups

/aws/codebuild/***
/aws/lambda/***

A new version of cw is available! - 1.7.0 -> v1.7.0
```

I tried both install `go get` and `brew`.

**Comment by lucagrulla** [comment]
Apologies,
that was an error in the code.

Please install V1.7.1 (just released).

**Comment by jnst** [comment]
It works! Thank you!
