### ISSUE TITLE
Tailing non-existent streams may `panic: send on closed stream`

### ISSUE THREAD

**Issue by dekimsey** [lucagrulla/cw#173]
**Describe the bug**
Tailing can cause a panic on non-existent streams

**To Reproduce**
1. `cw tail -sf ams-es-high:warm/elasticsearch/elasticsearch.log/`

This log group doesn't yet have any streams matching this invocation. If I run again, it works fine, I'm guessing this is a race condition with the channel.

**Expected behavior**

Exits cleanly
```
No such log stream(s).
```

**Screenshots**

```
No such log stream(s).
panic: send on closed channel

goroutine 15 [running]:
github.com/lucagrulla/cw/cloudwatch.(*CW).Tail.func3(0xc00023e4c0, 0xc00023e401, 0x0)
	/Users/luca.grulla/Projects/cw/cloudwatch/tail.go:114 +0x1a0
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).FilterLogEventsPagesWithContext(0xc00035c020, 0x17e3640, 0xc0000b2008, 0xc000066900, 0xc0002de190, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/luca.grulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.31.4/service/cloudwatchlogs/api.go:2550 +0x163
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).FilterLogEventsPages(...)
	/Users/luca.grulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.31.4/service/cloudwatchlogs/api.go:2523
github.com/lucagrulla/cw/cloudwatch.(*CW).Tail.func4(0xc000439e00, 0xc0001f00e0, 0xc00008f8e0, 0xc0001d7560, 0xc0000b29a8, 0x0, 0xc00008f7c0, 0xc0000b2918, 0xc0004080b0, 0xc0002de190)
	/Users/luca.grulla/Projects/cw/cloudwatch/tail.go:138 +0x3b3
created by github.com/lucagrulla/cw/cloudwatch.(*CW).Tail
	/Users/luca.grulla/Projects/cw/cloudwatch/tail.go:133 +0x2c4
```

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - zsh

cw --version
3.3.0

**Additional context**

**Comment by lucagrulla** [comment]
Hi @dekimsey,

I'm not sure I understood it properly.
Is this a scenario where the log group exists  _but_ it does not have any log streams yet?

**Comment by dekimsey** [comment]
Yesish. The group exists, but the streams were not yet matching (the `warm/` prefix was just added).

So there were possible streams to tail, but none would have matched this filter when I ran it.

**Comment by lucagrulla** [comment]
By looking at the code, there's no obvious explanation for this error. I'm wondering if the problem is actually in the AWS sdk.
I see you were using V3.3.0. Could you try with the latest release, v4.0.x?

**Comment by dekimsey** [comment]
I'm sorry, I never replied. I haven't seen the issue again since updating. Thank you!
