### ISSUE TITLE
cw might not monitor the correct streams when there are more than 100

### ISSUE THREAD

**Issue by lucagrulla** [lucagrulla/cw#174]
**Describe the bug**
When more than 100 streams are present in a group, cw would need to pick 100 max due to limitation in the AWS FilterLogEventPages SDK. Currently `cw` will pick the first 100 returned from AWS. Those streams might not be active.

**Comment by dili91** [comment]
+1

**Comment by lucagrulla** [comment]
Fixed with V4.0.5
