### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by ronyeh-lb** [lucagrulla/cw#217]
**Describe the bug**
no output, only error exit code

**To Reproduce**
~ ❯ cw ls groups --profile=lb-prod
~ ❯ echo $?
1
also with --region

**Desktop
 - OS: [e.g. MacOS 10.15.7]
 - zsh
- aws cli v2 with valid profile and cred
- cw 4.1.0

**Comment by lucagrulla** [comment]
Is any other command (tail, ls streams) work?
I am wondering if the hyphen in the profile name confuses the AWS client. Can you try to set lb-prod as the default profile in the was credentials file and try again?

**Comment by ronyeh-lb** [comment]
other command doesn't work as well.
only validation error outputs when i omit some required parameters.
default profile doesn't work.

is there any verbose debug mode?
is there any method to brew install previous versions?

**Comment by lucagrulla** [comment]
Are you going through a proxy?

**Comment by ronyeh-lb** [comment]
no

**Comment by ronyeh-lb** [comment]
how can i install previous version ?

**Comment by ronyeh-lb** [comment]
found the issue !- parsing issue of .config
`
[default]
region=us-east-2
cli_pager=

[profile linearb-prod]
region=us-east-2
cli_pager=
`
there was no new line at the end, i added (press enter) and thats it.

**Comment by lucagrulla** [comment]
Great to hear!
