### ISSUE TITLE
The bottle: uneeded attribute is deprecated and must be removed from heracles.rb file in the lucagrulla/homebrew-tap repo

### ISSUE THREAD

**Issue by adarnois** [lucagrulla/cw#230]
** Description **
The bottle :uneeded attribue has to be removed from the heracles.rb file (line 9) of the https://github.com/lucagrulla/homebrew-tap project because it is a now a deprecated command and it prevents to install the lucagrulla/tap via the 'brew tap lucagrulla/tap' command on macOS. 

In fact, it provokes an Invalid Syntax error on macOS with Homebrew (tested on macOS Big 11.6.4 with Homebrew 3.3.16-64-g103cd0c) see below:

==> Tapping lucagrulla/tap
cloning into '/usr/local/Homebrew/Library/Taps/lucagrulla/homebrew-tap'...
remote: Enumerating objects: 385, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 385 (delta 0), reused 0 (delta 0), pack-reused 381
Receiving objects: 100% (385/385), 45.69 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (103/103), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/lucagrulla/homebrew-tap/Formula/heracles.rb
heracles: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the lucagrulla/tap tap (not Homebrew/brew or Homebrew/core):
/usr/local/Homebrew/Library/Taps/lucagrulla/homebrew-tap/Formula/heracles.rb:9

Error: Cannot tap lucagrulla/tap: invalid syntax in tap!

**To Reproduce**

Try to simply install  the lucagrulla/tap via Homebrew on macOs

brew tap lucagrulla/tap

**Expected behavior**

The lugacrulla/tap should work and the homebrew-tap folder should be installed inside the following folder:

/usr/local/Homebrew/Library/Taps/lucagrulla/

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.4
 - Homebrew release 3.3.16-64-g103cd0c
 - Terminal: zsh
 - Trying to install the 4.1.1 release

**Additional context**
N/A

**Comment by lucagrulla** [comment]
Thanks for raising this.
It should be fixed now. Give it another go and let me know if it works.

**Comment by adarnois** [comment]
Hi,

Thank you for the fix, I confirm it is well working now:

 ~  brew tap lucagrulla/tap                                                                                                   ✔  10034  10:05:50
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 28 formulae.

==> Tapping lucagrulla/tap
Cloning into '/usr/local/Homebrew/Library/Taps/lucagrulla/homebrew-tap'...
remote: Enumerating objects: 389, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 389 (delta 0), reused 0 (delta 0), pack-reused 381
Receiving objects: 100% (389/389), 46.65 KiB | 316.00 KiB/s, done.
Resolving deltas: 100% (103/103), done.
Tapped 2 formulae (15 files, 66.8KB).

 ~  brew install cw                                                                                                           ✔  10035  10:06:03
==> Downloading https://github.com/lucagrulla/cw/releases/download/v4.1.1/cw_4.1.1_Darwin_x86_64.tar.gz
Already downloaded: /Users/alexis/Library/Caches/Homebrew/downloads/aec770a508eccbb9602b7fcda3b206d409db958e1c1387074e116e7f90c38ee0--cw_4.1.1_Darwin_x86_64.tar.gz
==> Installing cw from lucagrulla/tap
==> Caveats
In order to get cw completion, [bash] you need to install `bash-completion` with brew. OR [zsh], add the following line to your ~/.zshrc: source /usr/local/share/zsh/site-functions/cw.zsh

zsh functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/cw/4.1.1: 7 files, 9.2MB, built in 6 seconds

**Comment by adarnois** [comment]
This case is closed
