### ISSUE TITLE
Use ldflags to overwrite hard-coded version at build time

### ISSUE THREAD

**Issue by kevinmichaelchen** [lucagrulla/cw#257]
I'm building a Tea package for this project here: https://github.com/teaxyz/pantry/pull/3085

Currently, `cw --version` reports an old version.

**Comment by lucagrulla** [comment]
Hi @kevinmichaelchen ,

I'm unsure about the issue you're flagging. Can you expand?

`cw` is built using `ldflags`.
The current version reported from my installation is 4.1.3; that is the latest one.

**Comment by kevinmichaelchen** [comment]
Hey @lucagrulla --

I'm seeing the latest [release](https://github.com/lucagrulla/cw/releases) as v1.4.3, but in the code I'm seeing 4.1.1 [hard-coded](https://github.com/lucagrulla/cw/blob/v4.1.3/main.go#L32).

**Comment by lucagrulla** [comment]
The code value is a placeholder, but the actual version is injected at build time with `ldflags`.

**Comment by lucagrulla** [comment]
I appreciate it might be confusing.
I will set the variable to `''`.

**Comment by kevinmichaelchen** [comment]
What is the name of the ldflag that overrides the version? 

I [couldn't find](https://github.com/search?q=repo%3Alucagrulla%2Fcw%20ldflags&type=code) anything in this repo.

**Comment by kevinmichaelchen** [comment]
Ah, sorry, `-X main.version` was **[what](https://github.com/teaxyz/pantry/pull/3085/commits/3fca491f621a848e9d27794916ebeb148845c5f4)** I was looking for.

Thanks for bearing with me. I'm still learning `ldflags`.

**Comment by lucagrulla** [comment]
I'm not sure I understand your question.

`ldflags` can be passed at linking time to `go build`:
`go build -ldflags="-X main.version=x.y.z"`

where `x.y.z` is the version you want to inject

`cw` uses `goreleaser` to create all the packages. goreleaser will inject the current git tag in the version variable.
https://goreleaser.com/cookbooks/using-main.version/
