### ISSUE TITLE
Clashing with AWS CodeWhisperer for command line

### ISSUE THREAD

**Issue by REBELinBLUE** [lucagrulla/cw#262]
Just reporting this as you may, or may not, want to do something about it but AWS CodeWhisperer for Command Line also installs a CLI `cw` so they clash

**Comment by Lewenhaupt** [comment]
Yeah quite annoying, and uncool of AWS. I solved it by creating an alias for the actual path of CodeWhisperer and placed `cw` first in the path.

**Comment by lucagrulla** [comment]
mhm, I'm not entirely sure how to fix the problem; renaming the entire thing could be an option, but it feels too drastic. Adding a paragraph to the README on "how to alias" could also be a good start.

**Comment by Lewenhaupt** [comment]
@lucagrulla yeah I think that's a good approach. Any other solution except for the renaming seems really complex and would probably not work reliably. For example doing the alias for CodeWhisperer when installing cw, but that would only work if CodeWhisperer was already installed.

**Comment by REBELinBLUE** [comment]
@lucagrulla @Lewenhaupt Seems that AWS have renamed `cw` to `q` anyway https://docs.aws.amazon.com/codewhisperer/latest/userguide/whisper-legacy.html :)

**Comment by Lewenhaupt** [comment]
Ah, nice! 😄
