### ISSUE TITLE
Make installation Linux friendly

### ISSUE THREAD

**Issue by lucagrulla** [lucagrulla/cw#27]
Which package manager to target?
Look into snapcraft

**Comment by franciscocpg** [comment]
How about using https://github.com/goreleaser/godownloader?

**Comment by lucagrulla** [comment]
Thanks,I'll look into it.

I still think that an established package manager will help.
My favourite solution at this stage is probably to make the brew recipe Linuxbrew friendly. 

https://github.com/goreleaser/goreleaser/issues/428 

I might look to send a PR on that to goreleaser.

**Comment by lucagrulla** [comment]
I  added snapcraft.io packaging and distributon 
I'll add also godownloader, but I'll manage it in a seperate issue ticket.
