### ISSUE TITLE
Package full name on Homebrew

### ISSUE THREAD

**Issue by jnst** [lucagrulla/cw#28]
I don't know if this is a mistake or not... I report you just in case.

`lucagrulla/cw/cw` -> `lucagrulla/cw` ?

```bash
$ brew info cw
lucagrulla/cw/cw: stable 2.1.1
```

```bash
$ brew upgrade cw
==> Upgrading 1 outdated package:
lucagrulla/cw/cw 2.1.0 -> 2.1.1
==> Upgrading lucagrulla/cw/cw
==> Downloading https://github.com/lucagrulla/cw/releases/download/v2.1.1/cw_2.1.1_Darwin_x86_64.tar.gz
```

**Comment by lucagrulla** [comment]
Improved by changing the naming strategy of the tap (homebrew-tap/cw instead of homebrew-cw/cw)

It will affect only for people using the new tap. 
The old tap will keep working as it is (so no forced migration to new tap).
