### ISSUE TITLE
Allow parameter for errors "Rate exceeded"

### ISSUE THREAD

**Issue by okelet** [lucagrulla/cw#33]
Sometimes, when the application is running multiple times, the error "Rate exceeded" is thrown and the application exits. It would be a good idea to have a parameter to continue, or add a delay, when that error happens.

**Comment by lucagrulla** [comment]
Hi,

Thanks for filing this issue.

Can you clarify what do you mean when you say " when the application is running multiple times"?

**Comment by okelet** [comment]
Hi! If I want to tail multiple log groups or multiple specific streams, I need to run `cw` in multiple terminal tabs/windows. It seems that AWS has some of limit request/throttling, that causes that error and the program exits. It is a temporary failure, because if I re-run the process that received the error, it continues tailing fine.

**Comment by lucagrulla** [comment]
Thanks for the clarification.
That's correct, AWS  limits on the number of API calls at account level (as your account). 

This is not a bug of the tool itself (the req rate is tailored to respect the throttling), it's a consequence of running the multiple instances.

Giving control of the req/rate won't be hard but it will end up in a less than ideal user experience, as no one will really know what's the right rate.

The suggestion @okelet made on issues #16 is probably a better approach. I might look into that.

**Comment by lucagrulla** [comment]
Best thing to do here is to handle te rate exceeded scenario better, by probably stop polling and restarting.

I'll look into that.

**Comment by lucagrulla** [comment]
V3.0.0 is solving this by allowing tailing of multiple groups from a single cw command. In this way there's full control on the request rate, avoiding to hit the per account/region AWS throttling.

**Comment by malammar** [comment]
Oftentimes I don't want my log group output mixed in one window. I think a request rate parameter would be useful as I don't need to tail very quickly on most of my requests.
