### ISSUE TITLE
SIGSEGV on APIgateway log group ls

### ISSUE THREAD

**Issue by mbeckner** [lucagrulla/cw#44]
Marks-MacBook-Pro[13:32:55] cw --profile=zjdevacct --region=us-east-2 ls streams "API-Gateway-Execution-Logs_72oi6rv36b/Alpha"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13d6c8b]

goroutine 8 [running]:
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1.1(0x1, 0x0, 0xc0000c3db8)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:24 +0x2b
sort.insertionSort_func(0xc0000c3e38, 0xc000487c00, 0x0, 0x14)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/zfuncversion.go:12 +0x93
sort.stable_func(0xc0000c3e38, 0xc000487c00, 0x32)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/zfuncversion.go:167 +0x51
sort.SliceStable(0x146ace0, 0xc000487be0, 0xc0000c3e38)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/slice.go:31 +0x106
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1(0xc00000b460, 0xc000030a00, 0xc0000556b8)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:23 +0x81
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPagesWithContext(0xc00000c270, 0x1a74188, 0xc0000260b0, 0xc000183320, 0xc000061820, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:1670 +0x116
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPages(0xc00000c270, 0xc000183320, 0xc000061820, 0x0, 0x0)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:1642 +0x90
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func2(0xc000061810, 0xc000183320, 0xc000061820)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:37 +0x49
created by github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:36 +0xf1

**Comment by lucagrulla** [comment]
Thanks for rasing this bug. 

I assume `ls streams` worka with other groups names? Or does it fail regardless the group for you?
Is by chance that group empty (as no log streams yet)?

**Comment by mbeckner** [comment]
I did not try with another log group. The group I accessed had several non-empty streams.

**Comment by lucagrulla** [comment]
Can you try with another log group? 

I can't see any problem in your command, and I'm struggling to replicate it with my log groups.

**Comment by mbeckner** [comment]
Only the API-Gateway log group is throwing the panic.

Marks-MacBook-Pro[12:25:05] awsdev --query logGroups[*].logGroupName  logs describe-log-groups
[
    "/aws/lambda/shipper-sam-ShipperHandlerFunction-155P3N3JNQEE4",
    "/aws/rds/instance/zj-dev-postgres/postgresql",
    **"API-Gateway-Execution-Logs_joekpkdl9f/Alpha",**
    "RDSOSMetrics"
]

===== API-Gateway =====

Marks-MacBook-Pro[12:27:45] cw --profile=zjdevacct --region=us-east-2 ls streams "API-Gateway-Execution-Logs_joekpkdl9f/Alpha"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13d6c8b]

goroutine 21 [running]:
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1.1(0x1, 0x0, 0xc0000d5db8)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:24 +0x2b
sort.insertionSort_func(0xc0000d5e38, 0xc000379b40, 0x0, 0x14)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/zfuncversion.go:12 +0x93
sort.stable_func(0xc0000d5e38, 0xc000379b40, 0x32)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/zfuncversion.go:167 +0x51
sort.SliceStable(0x146ace0, 0xc000379b20, 0xc0000d5e38)
	/usr/local/Cellar/go/1.11.5/libexec/src/sort/slice.go:31 +0x106
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1(0xc0000a5400, 0xc000094900, 0xc00004feb8)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:23 +0x81
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPagesWithContext(0xc00009e260, 0x1a782a0, 0xc000092020, 0xc00019b320, 0xc000081810, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:1670 +0x116
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPages(0xc00009e260, 0xc00019b320, 0xc000081810, 0x0, 0x0)
	/Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.14.17/service/cloudwatchlogs/api.go:1642 +0x90
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func2(0xc000081800, 0xc00019b320, 0xc000081810)
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:37 +0x49
created by github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams
	/Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:36 +0xf1

===== RDS log group =====

Marks-MacBook-Pro[12:28:57] cw --profile=zjdevacct --region=us-east-2 ls streams "/aws/rds/instance/zj-dev-postgres/postgresql"
zj-dev-postgres.0

===== Lambda log group =====

Marks-MacBook-Pro[12:29:49] cw --profile=zjdevacct --region=us-east-2 ls streams "/aws/lambda/shipper-sam-ShipperHandlerFunction-155P3N3JNQEE4"
2019/04/22/[$LATEST]be0bbbbfae6d473fadb3522c341a24aa
2019/04/22/[$LATEST]067580023a4c4ff5909adf5246b20b05
2019/04/22/[$LATEST]93d395598ffa4d3f87d49f2e1cef576b
~/Developer/ZoneJumpDev/GitHub/zj-shipper-api
Marks-MacBook-Pro[12:30:19]

**Comment by isundaylee** [comment]
Another data point: I encountered the same crash on Linux (amd64, installed from release .deb, Debian 10) when doing `cw ls streams docker`. It works fine for other groups (e.g. `/var/log/syslog`). Backtrace:

```
goroutine 9 [running]:
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1.1(0x2, 0x1, 0x1)
        /Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:24 +0x2d
sort.insertionSort_func(0xc000051e98, 0xc00044e580, 0x0, 0x14)
        /usr/local/Cellar/go/1.13/libexec/src/sort/zfuncversion.go:12 +0xb1
sort.stable_func(0xc000051e98, 0xc00044e580, 0x32)
        /usr/local/Cellar/go/1.13/libexec/src/sort/zfuncversion.go:167 +0x51
sort.SliceStable(0x910ae0, 0xc00044e560, 0xc000051e98)
        /usr/local/Cellar/go/1.13/libexec/src/sort/slice.go:27 +0xcb
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func1(0xc00000d360, 0xc00001ed00, 0x0)
        /Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:23 +0x8f
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPagesWithContext(0xc00000e250, 0xb634e0, 0xc000022108, 0xc00019e9c0, 0xc000057780, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.23.17/service/cloudwatchlogs/api.go:1662 +0x116
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPages(...)
        /Users/lucagrulla/go/pkg/mod/github.com/aws/aws-sdk-go@v1.23.17/service/cloudwatchlogs/api.go:1634
github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams.func2(0xc000057770, 0xc00019e9c0, 0xc000057780)
        /Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:37 +0x73
created by github.com/lucagrulla/cw/cloudwatch.(*CW).LsStreams
        /Users/lucagrulla/Projects/cw/cloudwatch/lsstreams.go:36 +0xf1
```

**Comment by isundaylee** [comment]
I looked into it a bit and it's due to `LastIngestionTime` being absent on line https://github.com/lucagrulla/cw/blob/4b481bf99df55e2df81b8e382282affff77f27b9/cloudwatch/lsstreams.go#L24

**Comment by isundaylee** [comment]
I made a quick fix here (https://github.com/isundaylee/cw/commit/dc777ef6b5ae033e54e64a9fd5ce76e73397578d). Let me know if you want me to make a PR.

By the way, thanks for making this! It works great other than this small hiccup.

**Comment by lucagrulla** [comment]
Thanks for digging this out and fixing it!
a PR is very welcome :-)

**Comment by isundaylee** [comment]
PR opened in #89

Thank you! :)
