### ISSUE TITLE
brew caveats wrong message 

### ISSUE THREAD

**Issue by aterreno** [lucagrulla/cw#6]
Once installed it tells you to add to source this file
` /usr/local/share/zsh/site-functions/_cw`

instead of 

` /usr/local/share/zsh/site-functions/cw`

```
==> Caveats

In order to get cw completion,
  [bash] you need to install `bash-completion` with brew.
  OR
  [zsh], add the following line to your ~/.zshrc:
    source /usr/local/share/zsh/site-functions/_cw

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh functions have been installed to:
  /usr/local/share/zsh/site-functions
```

**Comment by lucagrulla** [comment]
A PR for improving the doc for ZSH user is greatly welcome.

**Comment by lucagrulla** [comment]
fixed:
https://github.com/lucagrulla/homebrew-cw/commit/b18024a1988a6ed71530ffc15c8e62e4330b8908
