### ISSUE TITLE
linuxbrew: support arm

### ISSUE THREAD

**Issue by lucagrulla** [lucagrulla/cw#61]
**Describe the bug**
Current linuxbrew manifest doesn't support ARM architecture.

**Comment by lucagrulla** [comment]
Depending on:
https://github.com/goreleaser/goreleaser/issues/1052

**Comment by dawidd6** [comment]
It's already merged and released.

**Comment by lucagrulla** [comment]
Oh you're right!
I'll update configuration and release over the weekend.
Thanks for the help.

**Comment by lucagrulla** [comment]
ARM release available since v3.2.2.

**Comment by dawidd6** [comment]
Not really, look at the formula:

https://github.com/lucagrulla/homebrew-tap/blob/master/Formula/cw.rb

**Comment by lucagrulla** [comment]
ouch! 

Ok, at least now ARM artefacts are  available for download and manual install under the release.
I'll check what's happening with the formula.

**Comment by dawidd6** [comment]
I think it's an upstream bug, see my post here: https://github.com/goreleaser/goreleaser/pull/1113

**Comment by dawidd6** [comment]
Fix: https://github.com/goreleaser/goreleaser/pull/1140

**Comment by dawidd6** [comment]
@lucagrulla can you test latest release?

**Comment by lucagrulla** [comment]
I see a new ARM conditional branch in the brew formula. It should be ok now. 
@dawidd6 do you mind test it?

**Comment by dawidd6** [comment]
Seems to be alright now, just by looking at it. Can't test it rn tho, but it should work.

**Comment by lucagrulla** [comment]
Great! 
Thanks for the help.
