### ISSUE TITLE
Pretty Print JSON

### ISSUE THREAD

**Issue by keyneston** [lucagrulla/cw#70]
**Is your feature request related to a problem? Please describe.**

One of the amazing features of CloudWatch is the ability to log to JSON, and then build intelligant searches based upon the JSON output.

This means logs often endup as long single lines of JSON output:

```json
{"error": "this was an error", "level": "error", "data": {"key1": 1, "key2": 2}}
```

To make this better cloud watch takes the JSON and pretty prints it. `cw` outputs it as the line was put into cloudwatch.

It would be nice if `cw` detected if a line was JSON or not, and if JSON would pretty print it for easier reading. Possibly as a flag to enable/disable.

**Describe alternatives you've considered**
I'm not sure if there is an easy "fix". Normally I'd pipe the output to `jq` but that doesn't work since some automatic lambda and other input is not JSON.

Additionally pretty printing the JSON to cloudwatch doesn't work becasue then cloudwatch doesn't consider a JSON blob as a single JSON event but instead each line is a different text event.

**Comment by KennethWKZ** [comment]
if can pretty print this kind of output is convenience

`2019-09-28T16:00:42.646Z        03e64967-2efb-4a90-8dda-17a65366d13b    INFO  {"_logLevel":"info","msg":"Response body"}`

**Comment by lucagrulla** [comment]
Hi,
Thanks for this request. 

I might try to add this feature at a certain point but it's not top of priorities for me right now.
A good PR would be very welcome.

**Comment by lightbody** [comment]
+1 for this... not sure it even needs to be a core feature, but maybe just show in the docs how you can pipe it through to `jq` with a few examples? when I find the time to do this I'll post anything I get working here. Thanks for great utility, btw!

**Comment by keyneston** [comment]
@lightbody Thanks, I was inspired to look more into `jq` to see if there was a way to do this that I wasn't familiar with. Turns out you can do `jq -R 'fromjson? | select(type == "object")'` and it works. Suboptimal to having it built in but more than does the job for now.

**Comment by lucagrulla** [comment]
Thanks for doing some research @keyneston. 

One of the great features of `cw` is that it follows Unix philosphy, so it does pipe in and out nicely. 

I mark this as resolved for the time being; I'll eventually add some documentation on how use `cw` and `jq` together (as @lightbody suggested).

**Comment by lightbody** [comment]
The thing I haven't yet figured out is how to convert nicely over to CSV the way I want. Because pretty-printing as JSON is one thing, but what I _really_ want is to actually convert it back out to a table format that looks nice in my scrolling console. 

 It's mostly just an exercise in becoming a better `jq` user. See, `jq` has a `@csv` operator but I haven't figured out how to select out just the fields I want before converting it to a table. From there, I could then pipe the output to [`column`](https://stackoverflow.com/questions/1875305/command-line-csv-viewer) and I think it'd get the job done.

**Comment by lightbody** [comment]
Quick update: I just about how it figured out... just trying to grok how to get the CSV to pipe to `column` or `sed` something that can put some spacing into each of the columns.

`cw tail -f /ecs/my-service | jq -r '[.timestamp, .level, .logger, .mdc.user, .message] | @csv'`
