### ISSUE TITLE
Hide fields such as timestamp, group-name, stream-name with --no- option

### ISSUE THREAD

**Issue by kienpham2000** [lucagrulla/cw#77]
```
--no-timestamp        Don't print the event timestamp.
--no-event-id           Don't print the event Id.
--no-stream-name      Don't print the log stream name this event belongs to.
--no-group-name       Don't print the log log group name this event belongs to.

```

**Comment by lucagrulla** [comment]
Hi @kienpham2000 ,

Thank you for your submission.
Can you help me understand better what you mean?

The fields you highlighted are optional; if you don't want them printed just don't add the relevant flags to your command.

**Comment by kienpham2000** [comment]
@lucagrulla I'm looking something similar to this: 
https://github.com/jorgebastida/awslogs#json-logs

I'm using this to tail a Lambda log: 
`cw tail -f --start="2019-11-03T00:00:00" /aws/lambda/config-rule-approved-ami-only`

Here's the output, I don't want timestamp, event name to show up, I just care about the actual logging message: 

```2019-11-03T09:32:53.176Z	03d8c113-ddf1-469c-8fb1-f178799a5da4	INFO	event left scope  true

2019-11-03T09:32:53.176Z	03d8c113-ddf1-469c-8fb1-f178799a5da4	INFO	final compliance is  NOT_APPLICABLE

END RequestId: 03d8c113-ddf1-469c-8fb1-f178799a5da4

REPORT RequestId: 03d8c113-ddf1-469c-8fb1-f178799a5da4	Duration: 84.27 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 96 MB
```

**Comment by lucagrulla** [comment]
hi @kienpham2000,

`cw` by default print only the `message` field of the cloudwatch log entry. The other fields need to be required explicitly with a flag (`--timestamp`,`--event-id`,`--stream-name`,` --group-name`).

Based on the command line command you shared:
`cw tail -f --start="2019-11-03T00:00:00" /aws/lambda/config-rule-approved-ami-only`

The feature is already into `cw`;  it looks like it's the way you log information that is causing your problem.
