### ISSUE TITLE
`go get` installs version 1.7.2 

### ISSUE THREAD

**Issue by alimoeeny** [lucagrulla/cw#79]
**Describe the bug**
if you install cs by `go get  github.com/lucagrulla/cw` or `go get -u github.com/lucagrulla/cw` you get version 1.7.2 and will be stuck at that version. 

**To Reproduce**
just do `go get -u github.com/lucagrulla/cw` 
I have "go version go1.13.4 darwin/amd64" installed , on a mac with latests macos, in zsh, 

**Expected behavior**
able to get the latest version of cw which is 3.2.3

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2
 - Terminal zsh, in iTerm

**Comment by lucagrulla** [comment]
hi @alimoeeny,

Thanks for filing this bug.

I tried on bash (not zsh) and with an older version already on disk it failed (it didn't override the version).

Once I cleaned the src folder under the path I did not have any problem.
Do you mind checking if you have a previous version already in your path?

**Comment by alimoeeny** [comment]
hmm, thanks @lucagrulla  
I tried bash, 
removed my old cw, 
made sure there are no other copies of cw or the repository anywhere on my file system, 
removed go.mod and go.sum files from my home, 
same results :| 
maybe something is unusual about my setup, 
But it looks like always it defaults to `github.com/lucagrulla/cw v1.7.2` 
If you cannot reproduce it , please feel free to close this ticket, 
I'll reopen if I can figure out what is causing this.

**Comment by vandr0iy** [comment]
I think I found the relevant issue with golang: https://github.com/golang/go/issues/35732 
I solved it by invoking `go get -u github.com/lucagrulla/cw@master`

**Comment by kerma** [comment]
Please reopen.

`go get` for installation will be deprecated soon: https://golang.org/doc/go-get-install-deprecation

`go install github.com/lucagrulla/cw@latest` will currently install 1.7.2.

Trying to force some recent release will result in: 

```
$ go install -v github.com/lucagrulla/cw@v4.1.0

go install: github.com/lucagrulla/cw@v4.1.0: github.com/lucagrulla/cw@v4.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```

**Comment by Pitasi** [comment]
@kerma I understand it's ideal, but it the meantime you can use `go install github.com/lucagrulla/cw@master`

@lucagrulla
