### ISSUE TITLE
Double newline

### ISSUE THREAD

**Issue by fleaz** [lucagrulla/cw#86]
**Describe the bug**
I'm running the latest cw release (3.2.2) and there is an superfluous linebreak after every log line.

**To Reproduce**
Happens to me with all `tail` commands

**Expected behavior**
There shouldn't be an extra newline between each log line

**Screenshots**
<img width="116" alt="Screenshot 2019-12-11 at 17 13 55" src="https://user-images.githubusercontent.com/2489598/70638931-01142600-1c3a-11ea-8452-73b64652556a.png">

**Desktop (please complete the following information):**
 - OS: macos 10.15.1
 - Terminal: zsh 5.7.1 in iTerm2 3.3.7

Best regards,
Felix

**Comment by lucagrulla** [comment]
Hi @fleaz,
I could not observe this behaviour in any log file I tailed.

Are you sure the (extra) newline is not introduced as part of writing the log?

**Comment by fleaz** [comment]
I tested a few other streams and it seems like this bug is only happening for Lambda logs. Looking at loggroups from other sources, I  don't hit this bug.

I'm quite sure that there are no extra newlines in the log, because it looks fine when I check the AWS Console

**Comment by lucagrulla** [comment]
`cw` does add a single new line after each log event when it prints out  on the shell.
I will test  with lambdas, but even if it's proved it's just lambdas is more about how lambdas write new events to the log then how `cw` prints them out in the terminal.

**Comment by radix** [comment]
codebuild also seems to include newlines in their log entries.

**Comment by lucagrulla** [comment]
It looks like this is based on how the upstream log is created, not a problem with the tool. 
I am closing the issue.
