### ISSUE TITLE
List IAM permissions needed to use CW

### ISSUE THREAD

**Issue by anafaggiano** [lucagrulla/cw#98]
- After downloading cw, I was not able to execute any of the command listed in the documentation, including `cw ls groups`. I ultimately want to run `cw tail`.

- I'm getting a `The security token included in the request is invalid.` error.

- I was allowed full access to Cloudwatch logs, and my aws creds are correct since I was able to use aws cli.

We provide our IAM permissions based on needs, and I can't figure out the permissions needed to use cw.

It'd be great if there was some guidance for the needed IAM roles somewhere. In the documentation somewhere like in the Readme, or as a `cw -list-permissions` or a `cw -list-iam` command. 

I went through the codebase and found some mention of ec2 roles, but again I can't tell which ones.

Thank you!

Update: Rotating my access keys allowed me access. Why though

**Comment by lucagrulla** [comment]
Great to hear you solved the problem. 
I'll consider if better capturing IAM permissions in the doc is feasable. Thanks for the suggestion.
